name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Clean previous builds
      run: ./gradlew clean --no-daemon
    
    - name: Download dependencies
      run: ./gradlew dependencies --no-daemon
    
    - name: Build development JAR
      run: ./gradlew build --no-daemon
    
    - name: Remap to production JAR
      run: ./gradlew remapJar --no-daemon
    
    - name: Check generated files
      run: |
        echo "=== 检查构建目录 ==="
        find build/ -name "*.jar" -type f | xargs ls -la
        echo "=== JAR文件详情 ==="
        find build/ -name "*.jar" -exec echo "File: {}" \; -exec unzip -l {} \; || true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mod-build
        path: |
          build/libs/*.jar
          build/reports/**
        retention-days: 30
